spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  config-location: classpath:mybatis-config.xml